[project]
name = "scripts"
version = "0.1.0"
description = ""
authors = [
    {name = "Sergey Mironov",email = "ka6ah505@gmail.com"}
]
readme = "README.md"
package-mode = false
requires-python = ">=3.11"
dependencies = [
    "httpx (>=0.28.1,<0.29.0)",
    "pandas (>=2.3.2,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
